"""Added created_by column to History

Revision ID: 1ebae586bdcf
Revises: bf5a236a5b3d
Create Date: 2025-08-06 14:59:00.111463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ebae586bdcf'
down_revision = 'bf5a236a5b3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('history', schema=None) as batch_op:
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###
