"""Add is_approved field to Employee

Revision ID: bf5a236a5b3d
Revises: 
Create Date: 2025-08-04 19:27:31.242325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf5a236a5b3d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_history')
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('is_approved')

    op.create_table('order_history',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('table_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('items', sa.VARCHAR(length=200), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
